config/routes.rb
Rails.application.routes.draw do

  resources :gossips

  resources :author

  resources :welcome

  resources :cities

  resources :sessions

  root 'gossips#index'

  get 'dashboard', to: 'dashboard#login'

  get 'staticpage/contact', to: 'static_pages#contact'

  get 'staticpage/team', to: 'static_pages#team'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users

	validates :name, presence: true 

end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

	validates :title, presence: {message: "Bonjour! Veux-tu bien renseigner un titre pour ton Gossip STP ?"}
	validates :title, uniqueness: true
	validates :title, length: {minimum: 3, maximum: 20, message: "Veux-tu bien renseigner un contenu un chouya plus long stp."}

	validates :content, presence: {message: "Bonjour! Veux-tu bien renseigner un titre pour ton Gossip STP ?"}
	validates :content, length: {minimum: 20, message: "Veux-tu bien renseigner un contenu un chouya plus long stp."}

end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"

	validates :first_name, presence:  {message: "Bonjour! Veux-tu bien renseigner ton prénom STP ?"}

	validates :last_name, presence:  {message: "Bonjour! Veux-tu bien renseigner ton nom STP ?"}

	validates :description, presence:  {message: "Bonjour! Veux-tu bien renseigner une description STP ?"}
	validates :description, length: {minimum: 20, message: "La description est trop courte."}

	validates :email, presence:  {message: "Bonjour! Veux-tu bien renseigner ton email STP ?"}
	validates :email, uniqueness: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Le dormat n'est pas correct. Renseigne un fomat d'adresse mail valide stp." }

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


include SessionsHelper
before_action :authenticate_user

def authenticate_user
unless current_user == true
flash [:danger] = "You must login to create a gossip"
redirect_to new_session_path
end
end

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossip = Gossip.all
    @user = User.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip = Gossip.all
    @user = User.all

  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)


  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
   @gossip = Gossip.new('title' => params[:title], 'content' => [content, 'user' => User.find(12)])
    if @gossip.save
      redirect_to gossips_path
    else
      render 'gossips/new'
    end

  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:title], content: params[:content])
      redirect_to gossips_path
    else
      render :edit
    end

  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossipp = Gossip.find(params[:id])
      if @gossipp.destroy
        redirect_to gossips_path
      else
        render :show
      end
  end

end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autheur_helper.rb
module AutheurHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def current_user
User.find_by(id: sessions [:user_id])
end

def log_in(user)
session[:user_id] = user.id
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<center>
    <%= form_tag url_for(action:'update'), method: "patch" do %>

      <%= label_tag 'Title' %><br>
      <%= text_field_tag 'title'  %>
      <br /> <br />

      <%= label_tag 'Content' %><br>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Modifier un Gossip" %>

    <% end %>
</center>

app/views/gossips/index.html.erb
<br><br><br>
<h1 style="text-align:center;">Balance ton Gossip</h1>
<br>
<h3 style="text-align:center;"><a class="btn btn-dark" href="/gossips/new">Clique ICI</h3></a>
<br>
<p style="text-align:center;"><i>PS: Ferme la porte y'a la pookie dans le sas -Lavoisier</i></p>
<br>
<% @gossip.each do |g| %>
<center>
  <div class="card" style="width: 18rem; text-align:center;">
    <img class="card-img-top" src="https://wallpapercave.com/wp/2RQ8Phs.jpg" alt="secret image">
    <div class="card-body">
     <a class="card-title"> <%=g.title %> </a>
      <p class="card-text"> <% a = g.user_id %> De : <%= @user.find(a).first_name %></p>
      <a class="btn btn-dark" href="http://localhost:3000/gossips/<%=g.id%>">Voir le Gossip !</a>
    </div>
<%end%>
  </div>
  <br>
</center>

<div class ="jumbotron jumbotron-fluid">
<div class ="container">
<h1 class= "ml11">
<span class ="text-wrapper">
<div style = "padding-top: 60px;">
<>
</span>
</span>

app/views/gossips/new.html.erb
<% if params[:gossip_title] == "" or params[:gossip_content] == ""%>
            <div class="alert alert-danger text-center" role="alert">
                  <strong>Un ou plusieurs champ(s) manquant(s)</strong>
                  <ul class="text-left">
                    <% if params[:gossip_title] == "" %>
                      <li>Auteur manquant</li>
                    <% end %>
                    <% if params[:gossip_content] == "" %>
                        <li>Contenu manquant</li>
                    <% end %>
                  </ul>
            </div>
        <% elsif params[:gossip_title] and params[:gossip_content]%>
            <div class="alert alert-success text-center" role="alert">
                 Gossip crée avec succés !
            </div>
        <%end%>

<div style="text-align:center; margin-top:100px;">

    <%= form_tag url_for(action:'create'), method: "post" do %>

      <%= label_tag 'GossipTitle' %><br>
      <%= text_field_tag 'title'  %>
      <br /> <br />

      <%= label_tag 'GossipContent' %><br>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Créer un gossip" %>

    <% end %>

</div>

app/views/gossips/show.html.erb
<center>
<div style="background-color:medium-grey;" class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 style="margin-top:40px;" class="display-3"><strong>GOSSIP n °<%= @gossip.find(params[:id]).id %>:</strong> <%= @gossip.find(params[:id]).title%></h1>
    <h2> Voilà toutes les infos sur le <%= @gossip.find(params[:id]).id %> ème Gossip !</h2>
  </div>
</div>
</center>


<div style ="margin-top:40px">
<center>
<h2 style=<strong>Titre : </strong><i><%= @gossip.find(params[:id]).title%></i></h2>
<br>
<p style=<strong>Contenu :</strong> <%= @gossip.find(params[:id]).content%></p>
<p style=<strong>Créé le :</strong> <%= @gossip.find(params[:id]).created_at%></p>
<p style=<strong>Auteur :</strong> <% g = @gossip.find(params[:id]) %> <% h = g.user_id %> <%= @user.find(h).first_name%> <%= @user.find(h).last_name%></p>
  <a href="<%=edit_gossip_path%>" class="btn btn-outline-dark"> Modifier le gossip </a>
  <%=form_tag url_for(action:'destroy'), method: "DELETE" do %>
  <% end %>
</center>
</div>

<br>

<center>
  <a href="<%=author_path(h)%>" class="btn btn-outline-dark">Profil de l'auteur </a>
  <a href="<%=city_path(@user.find(h).city_id)%>" class="btn btn-outline-dark">Ville de l'auteur </a>
  <br><br>
</center>