config/routes.rb
Rails.application.routes.draw do

  resources :gossips

  resources :author

  resources :welcome

  resources :cities

  resources :sessions

  root 'gossips#index'

  get 'dashboard', to: 'dashboard#login'

  get 'staticpage/contact', to: 'static_pages#contact'

  get 'staticpage/team', to: 'static_pages#team'


end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users

	validates :name, presence: true 

end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

	validates :title, presence: {message: "Bonjour! Veux-tu bien renseigner un titre pour ton Gossip STP ?"}
	validates :title, uniqueness: true
	validates :title, length: {minimum: 3, maximum: 20, message: "Veux-tu bien renseigner un contenu un chouya plus long stp."}

	validates :content, presence: {message: "Bonjour! Veux-tu bien renseigner un titre pour ton Gossip STP ?"}
	validates :content, length: {minimum: 20, message: "Veux-tu bien renseigner un contenu un chouya plus long stp."}

end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"

	validates :first_name, presence:  {message: "Bonjour! Veux-tu bien renseigner ton prénom STP ?"}

	validates :last_name, presence:  {message: "Bonjour! Veux-tu bien renseigner ton nom STP ?"}

	validates :description, presence:  {message: "Bonjour! Veux-tu bien renseigner une description STP ?"}
	validates :description, length: {minimum: 20, message: "La description est trop courte."}

	validates :email, presence:  {message: "Bonjour! Veux-tu bien renseigner ton email STP ?"}
	validates :email, uniqueness: true
	validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Le dormat n'est pas correct. Renseigne un fomat d'adresse mail valide stp." }

end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/autheur_helper.rb
module AutheurHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def current_user
User.find_by(id: sessions [:user_id])
end

def log_in(user)
session[:user_id] = user.id
end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<header>
<nav class="navbar navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">TheGossipProject</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=staticpage_team_path%>">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=staticpage_contact_path%>">Contact</a>

      </li>
    </ul>
  </div>
</nav>
</header>
    <%= yield %>
  </body>
</html>